name: Build

on: push

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: pnpm

    - name: pnpm install
      run: pnpm install 

    # - name: Build
    #   run: pnpm run build
      
    - name: pnpm run deploy
      run: NPM_TOKEN=${{secrets.NPM_TOKEN}} pnpm run deploy